### PR TITLE
Support for Redis in a Cluster and Sentinels layout

### PR DESCRIPTION
**Pull request by bgrieder**
Tests for each layout are available in

 - cluster: `test/cluster.mocha.js`  (ioredis driver)
 - sentinel: `sntinels.mocha.js` (ioredis driver)
 - direct: `direct.noderedis.mocha.js` and  `direct.ioredis.mocha.js`

Running the cluster tests require the ability to run the Ruby code in `test/redis-trib.rb` which is a Redis provided helper to create a cluster.

Code that could be further improved:

 - Remove layout specific tests in `connection.js` and `bus.js` by normalizing the exposed client in `driver.js`  (as is done for `getInfo()`)

 - Improve the redis start-ups and shutdowns in tests: when a test fails, Redis does not shut down properly. Also it is hard to run the test in sequence. This is because the `bus` detects shutdown of Redis instances, and starts emitting errors which are further caught as errors by the tests. Tof fix this, the there mus be a way of programatically shutting down Redis without triggering bus errors.

### CODE REVIEW

**Comment by fujifish** [comment]
THANK YOU!
This is a huge contribution to busmq.
I had to make some changes in the tests to make it compatible with node 0.10.

Version 1.4.0 was released to npm.

**Comment by kpturner** [comment]
Will there be documentation on how to make use of it?

**Comment by fujifish** [comment]
Yes

-- nadav

**Comment by fujifish** [comment]
Readme was updated with details.

```javascript
var Bus = require('busmq');

// default connection options
var bus = Bus.create({redis: ['redis://192.168.0.1:6379', 'redis://authpass@192.168.0.2:6379']);

// specify the node-redis driver explicitly
var bus = Bus.create({driver: 'node-redis', redis: ['redis://192.168.0.1:6379', 'redis://authpass@192.168.0.2:6379']);

// specify the ioredis driver explicitly
var bus = Bus.create({driver: 'ioredis', redis: ['redis://192.168.0.1:6379', 'redis://authpass@192.168.0.2:6379']);

// specify the ioredis driver and cluster
var bus = Bus.create({driver: 'ioredis', layout: 'cluster', redis: ['redis://192.168.0.1:6379', 'redis://authpass@192.168.0.2:6379']);

// specify the ioredis driver and sentinels
var bus = Bus.create({driver: 'ioredis', layout: 'sentinels', redis: ['redis://192.168.0.1:26379']);
```

**Pull request merged**
