### PR TITLE
automatic browser lib rebuild on postinstall

### PR DESCRIPTION
**Pull request by tlenex**
What do you think about it?

### CODE REVIEW

**Comment by fujifish** [comment]
Only thing is that I don't want browserify and uglify as runtime dependencies, so I'm not I feel comfortable merging this in.

**Comment by tlenex** [comment]
Maybe just mentioning those two in `README.md` with `-g` flag will be enough, shall i update my PR? Either way your lib build script depends on them.

**Comment by tlenex** [comment]
Updated, please recheck

**Comment by fujifish** [comment]
updated readme and added build deps to dev dependencies. I hope this works for you.

**Comment by tlenex** [comment]
thank you!

**Pull request closed without merging**
